service: invest-tracker-api
app: invest-tracker
#org: silas-stoffel

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '^4.15.0'

plugins:
  - serverless-offline

custom:
    serverless-offline:
        noPrependStageInUrl: true

provider:
  name: aws
  runtime: provided.al2023
  architecture: x86_64

# you can overwrite defaults here
  stage: ${opt:stage, 'dev'}
  region: us-east-1

  logRetentionInDays: 1

  deploymentBucket:
    # On deployment, serverless prunes artifacts older than this limit (default: 5)
    maxPreviousDeploymentArtifacts: 3

# you can add statements to the Lambda function's IAM Role here
#  iam:
#    role:
#      statements:
#        - Effect: "Allow"
#          Action:
#            - "sqs:SendMessage"
#          Resource:
#            - Fn::GetAtt: [createInvestmentQueue, Arn]
  

package:
  individually: true
  patterns:
    - '!./**'
    - ./bin/**

resources:
  Resources:

    createInvestmentQueueDQL:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: create-investment-${opt:stage, 'dev'}-dlq

    createInvestmentQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: create-investment-${opt:stage, 'dev'}
        VisibilityTimeout: 30
        RedrivePolicy:
          deadLetterTargetArn:
            Fn::GetAtt: [createInvestmentQueueDQL, Arn]
          maxReceiveCount: 3

    calculateAveragePriceQueueDQL:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: calculate-average-price-${opt:stage, 'dev'}-dlq.fifo
        FifoQueue: true

    calculateAveragePriceQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: calculate-average-price-${opt:stage, 'dev'}.fifo
        FifoQueue: true
        VisibilityTimeout: 30
        RedrivePolicy:
          deadLetterTargetArn:
            Fn::GetAtt: [calculateAveragePriceQueueDQL, Arn]
          maxReceiveCount: 10

    scheduleInvestmentLambdaRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service: lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: ScheduleInvestmentPolicy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - sqs:SendMessage
                  Resource:
                    - Fn::GetAtt: [createInvestmentQueue, Arn]
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource: "*"

    createInvestmentLambdaRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service: lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: CreateInvestmentLambdaPolicy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - sqs:ReceiveMessage
                    - sqs:DeleteMessage
                    - sqs:GetQueueAttributes
                  Resource:
                    - Fn::GetAtt: [createInvestmentQueue, Arn]
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource: "*"
                - Effect: Allow
                  Action:
                    - sqs:SendMessage
                  Resource:
                    - Fn::GetAtt: [createInvestmentQueueDQL, Arn]
                - Effect: Allow
                  Action:
                    - sqs:SendMessage
                  Resource:
                    - Fn::GetAtt: [calculateAveragePriceQueue, Arn]                    

    calculateAveragePriceLambdaRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service: lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: CalculateAveragePriceLambdaPolicy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - sqs:ReceiveMessage
                    - sqs:DeleteMessage
                    - sqs:GetQueueAttributes
                  Resource:
                    - Fn::GetAtt: [calculateAveragePriceQueue, Arn]
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource: "*"
                - Effect: Allow
                  Action:
                    - sqs:SendMessage
                  Resource:
                    - Fn::GetAtt: [calculateAveragePriceQueueDQL, Arn]                     

functions:
  schedule-investment:
    description: "Lambda function to schedule investments"
    role: scheduleInvestmentLambdaRole
    handler: bin/bootstrap
    name: schedule-investment-${opt:stage, 'dev'}
    memorySize: 128	
    environment:
      ENVIRONMENT: ${opt:stage, 'dev'}
      CREATE_INVESTMENT_QUEUE_URL: https://sqs.us-east-1.amazonaws.com/${aws:accountId}/create-investment-${opt:stage, 'dev'}
    package:
      artifact: ./bin/schedule-investment.zip
    events:
      - http:
          path: /investments/schedule
          method: post

  create-investment:
    description: "Lambda function to create investments"
    role: createInvestmentLambdaRole
    handler: bin/bootstrap
    name: create-investment-${opt:stage, 'dev'}
    memorySize: 256
    timeout: 30
    environment:
      ENVIRONMENT: ${opt:stage, 'dev'}
      CALCULATE_AVERAGE_PRICE_QUEUE_URL: https://sqs.us-east-1.amazonaws.com/${aws:accountId}/calculate-average-price-${opt:stage, 'dev'}.fifo
      TELEGRAM_TOKEN: ${ssm(raw):/invest-track-${opt:stage, 'dev'}/telegram/bot-token}
      TELEGRAM_CHAT_ID: 98047971
      CLOUDFLARE_API_KEY: ${ssm(raw):/invest-track-${opt:stage, 'dev'}/cloudflare/api-key}
      CLOUDFLARE_ACCOUNT_ID: ${ssm(raw):/invest-track-${opt:stage, 'dev'}/cloudflare/account-id}
      CLOUDFLARE_DB_ID: ${ssm(raw):/invest-track-${opt:stage, 'dev'}/cloudflare/db-id}
    package: 
      artifact: ./bin/create-investment.zip
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - createInvestmentQueue
              - Arn
          batchSize: 5
          maximumBatchingWindow: 5
          functionResponseType: ReportBatchItemFailures

  calculate-average-price:
    description: "Lambda function to calculate average price"
    role: calculateAveragePriceLambdaRole
    handler: bin/bootstrap
    name: calculate-average-price-${opt:stage, 'dev'}
    memorySize: 128
    timeout: 30
    environment:
      ENVIRONMENT: ${opt:stage, 'dev'}
      TELEGRAM_TOKEN: ${ssm(raw):/invest-track-${opt:stage, 'dev'}/telegram/bot-token}                        
      TELEGRAM_CHAT_ID: 98047971
      CLOUDFLARE_API_KEY: ${ssm(raw):/invest-track-${opt:stage, 'dev'}/cloudflare/api-key}
      CLOUDFLARE_ACCOUNT_ID: ${ssm(raw):/invest-track-${opt:stage, 'dev'}/cloudflare/account-id}
      CLOUDFLARE_DB_ID: ${ssm(raw):/invest-track-${opt:stage, 'dev'}/cloudflare/db-id}
    package: 
      artifact: ./bin/calculate-average-price.zip
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - calculateAveragePriceQueue
              - Arn
          batchSize: 1
          functionResponseType: ReportBatchItemFailures

  due-date-notifier:
    description: "Notify when investment due date is coming"
    handler: bin/bootstrap
    name: due-date-notifier-${opt:stage, 'dev'}
    memorySize: 128	
    environment:
      ENVIRONMENT: ${opt:stage, 'dev'}
      TELEGRAM_TOKEN: ${ssm(raw):/invest-track-${opt:stage, 'dev'}/telegram/bot-token}
      TELEGRAM_CHAT_ID: 98047971
      CLOUDFLARE_API_KEY: ${ssm(raw):/invest-track-${opt:stage, 'dev'}/cloudflare/api-key}
      CLOUDFLARE_ACCOUNT_ID: ${ssm(raw):/invest-track-${opt:stage, 'dev'}/cloudflare/account-id}
      CLOUDFLARE_DB_ID: ${ssm(raw):/invest-track-${opt:stage, 'dev'}/cloudflare/db-id}      
    package:
      artifact: ./bin/due-date-notifier.zip
    events:
      - schedule:
          #rate: rate(2 minutes)
          rate: cron(30 10 ? * SUN *)

  get-investment-summary-by-symbol:
    description: "Get investment summary by symbol"
    #role: scheduleInvestmentLambdaRole
    handler: bin/bootstrap
    name: get-investment-summary-by-symbol-${opt:stage, 'dev'}
    memorySize: 128	
    environment:
      ENVIRONMENT: ${opt:stage, 'dev'}
    package:
      artifact: ./bin/get-investment-summary-by-symbol.zip
    events:
      - http:
          path: /investments/summary/{symbol}
          method: get