service: invest-tracker-api
# app and org for use with dashboard.serverless.com
app: invest-tracker
#org: silas-stoffel

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '^4.15.0'

plugins:
  - serverless-offline

custom:
    serverless-offline:
        noPrependStageInUrl: true

provider:
  name: aws
  runtime: provided.al2023
  architecture: x86_64

# you can overwrite defaults here
  stage: ${opt:stage, 'dev'}
  region: us-east-1

# you can add statements to the Lambda function's IAM Role here
#  iam:
#    role:
#      statements:
#        - Effect: "Allow"
#          Action:
#            - "s3:ListBucket"
#          Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#        - Effect: "Allow"
#          Action:
#            - "s3:PutObject"
#          Resource:
#            Fn::Join:
#              - ""
#              - - "arn:aws:s3:::"
#                - "Ref" : "ServerlessDeploymentBucket"
#                - "/*"

# you can define service wide environment variables here
#  environment:
#    variable1: value1

package:
  individually: true
  patterns:
    - '!./**'
    - ./bin/**

functions:
  create-investment:
    handler: bin/bootstrap
    name: create-investment-${opt:stage, 'dev'}
    package:
      artifact: ./bin/create-investment.zip
    events:
      - http:
          path: /investments
          method: post
