service: invest-tracker-api
# app and org for use with dashboard.serverless.com
app: invest-tracker
#org: silas-stoffel

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '^4.15.0'

plugins:
  - serverless-offline

custom:
    serverless-offline:
        noPrependStageInUrl: true

provider:
  name: aws
  runtime: provided.al2023
  architecture: x86_64

# you can overwrite defaults here
  stage: ${opt:stage, 'dev'}
  region: us-east-1

  logRetentionInDays: 1

# you can add statements to the Lambda function's IAM Role here
#  iam:
#    role:
#      statements:
#        - Effect: "Allow"
#          Action:
#            - "sqs:SendMessage"
#          Resource:
#            - Fn::GetAtt: [createInvestmentQueue, Arn]

# you can define service wide environment variables here
#  environment:
#    variable1: value1

package:
  individually: true
  patterns:
    - '!./**'
    - ./bin/**

resources:
  Resources:

    createInvestmentQueueDQL:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: create-investment-${opt:stage, 'dev'}-dlq

    createInvestmentQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: create-investment-${opt:stage, 'dev'}
        RedrivePolicy:
          deadLetterTargetArn:
            Fn::GetAtt: [createInvestmentQueueDQL, Arn]
          maxReceiveCount: 3

    scheduleInvestmentLambdaRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service: lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: ScheduleInvestmentPolicy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - sqs:SendMessage
                  Resource:
                    - Fn::GetAtt: [createInvestmentQueue, Arn]
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource: "*"

    createInvestmentLambdaRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service: lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: CreateInvestmentLambdaPolicy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - sqs:ReceiveMessage
                    - sqs:DeleteMessage
                    - sqs:GetQueueAttributes
                  Resource:
                    - Fn::GetAtt: [createInvestmentQueue, Arn]
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource: "*"

functions:
  schedule-investment:
    description: "Lambda function to schedule investments"
    role: scheduleInvestmentLambdaRole
    handler: bin/bootstrap
    name: schedule-investment-${opt:stage, 'dev'}
    memorySize: 128	
    environment:
      CREATE_INVESTMENT_QUEUE_URL: https://sqs.us-east-1.amazonaws.com/${aws:accountId}/create-investment-${opt:stage, 'dev'}
    package:
      artifact: ./bin/schedule-investment.zip
    events:
      - http:
          path: /investments/schedule
          method: post

  create-investment:
    description: "Lambda function to create investments"
    role: createInvestmentLambdaRole
    handler: bin/bootstrap
    name: create-investment-${opt:stage, 'dev'}
    memorySize: 256
    timeout: 60
    environment:
      MONGO_URL: the-mongo-url-${opt:stage, 'dev'}
    package: 
      artifact: ./bin/create-investment.zip
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - createInvestmentQueue
              - Arn
          batchSize: 10
          maximumBatchingWindow: 5
